/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as AboutImport } from './routes/about'
import { Route as AllJobsImport } from './routes/AllJobs'
import { Route as AddNewJobImport } from './routes/AddNewJob'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AllJobsRoute = AllJobsImport.update({
  path: '/AllJobs',
  getParentRoute: () => rootRoute,
} as any)

const AddNewJobRoute = AddNewJobImport.update({
  path: '/AddNewJob',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/AddNewJob': {
      preLoaderRoute: typeof AddNewJobImport
      parentRoute: typeof rootRoute
    }
    '/AllJobs': {
      preLoaderRoute: typeof AllJobsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AddNewJobRoute,
  AllJobsRoute,
  AboutRoute,
  ProfileRoute,
])

/* prettier-ignore-end */
